Hide tournament matches if game is not selected.
blinkesport/gewaer-cms pull request #32
Opened 2019-10-17 20:02 UTC by javieracevedo

2019-10-17 20:03 UTC, javieracevedo commented on src/components/forms/match/teams-form.vue
> +                        search-field="sda"
```suggestion
```

2019-10-17 20:03 UTC, javieracevedo commented on src/components/forms/match/teams-form.vue
> +                        filter-fields="ad"
```suggestion
```

2019-10-17 20:20 UTC, SparoHawk requested changes

2019-10-17 20:20 UTC, SparoHawk commented on src/components/forms/match/index.vue
> +                <teams-form v-if="!isMatchesDisabled" />
```suggestion
                <teams-form v-if="match.game !== null" />
```

2019-10-17 20:20 UTC, SparoHawk commented on src/components/forms/match/index.vue
>          }
Remove.

2019-10-17 20:20 UTC, SparoHawk commented on src/components/forms/match/index.vue
> +            matchGame: state => state.Match.data.game
Remove.

2019-10-17 20:20 UTC, SparoHawk commented on src/components/forms/match/teams-form.vue
> +import { mapState } from "vuex";
Remove.

2019-10-17 20:20 UTC, SparoHawk commented on src/components/forms/match/teams-form.vue
> +        }),
Remove.

2019-10-18 15:59 UTC, SparoHawk approved these changes

2019-10-18 15:59 UTC, merged