If an image was inserted the input event was not emitted because the …
blinkesport/gewaer-cms pull request #36
Opened 2019-12-27 17:27 UTC by javieracevedo

…source of this change is made trough the API instead of the user directly. Now we emit the input event when the source of the change is from the API and the html as an inner image.

2019-12-27 17:31 UTC, DannyFeliz requested changes

2019-12-27 17:31 UTC, DannyFeliz commented on src/components/quill-wrapper/quill-wrapper.vue
> +                if (source === "user" || source === "api") {
```suggestion
                if (["user", "api"].includes(source)) {
```

2019-12-27 19:25 UTC, SparoHawk requested changes

2019-12-27 19:25 UTC, SparoHawk commented on src/components/quill-wrapper/quill-wrapper.vue
> +                    if (this.hasInnerText(textHTML) || this.hasInnerImage(textHTML)) {
```suggestion
                    if (this.hasInnerText(textHTML) || textHTML.includes("<img")) {
```

Since Quill transforms any typed < or > to the HTML entities `&lt;` and `&gt;` you can safely ask specifically for the image opening tag.

2019-12-27 19:25 UTC, SparoHawk commented on src/components/quill-wrapper/quill-wrapper.vue
> +            return innerImage != null;
You can remove this method.

2019-12-27 19:25 UTC, SparoHawk commented on src/components/quill-wrapper/quill-wrapper.vue
> +        },
```suggestion
        }
```

2019-12-27 19:33 UTC, SparoHawk requested changes

2019-12-27 19:33 UTC, SparoHawk commented on src/components/quill-wrapper/quill-wrapper.vue
> +                    this.$emit("input", "");
```suggestion
                    const quillContainer = this.quill.container.firstChild;
                    if (quillContainer.innerText || quillContainer.innerHTML.includes("<img")) {
                        this.$emit("input", quillContainer.innerHTML);
                    } else {
                    	this.$emit("input", "");
                    }
```

Since Quill transforms any typed < or > to the HTML entities `&lt;` and `&gt;` you can safely ask specifically for the image opening tag.

2020-01-08 17:57 UTC, SparoHawk approved these changes

2020-01-08 17:57 UTC, merged